// Fest hinterlegte, quellenbelegte Fakten pro Phase und Kategorie.
// Peer-reviewed wo möglich. Bei Klick auf "Hintergrundwissen" wird aus jeder
// Kategorie zufällig ein Fakt gezogen - kein Live-API-Call nötig, sofort verfügbar.

export const PHASE_FACTS = {
  menstruation: {
    body: [
      { text: { de: "Östrogen und Progesteron befinden sich auf ihrem niedrigsten Stand des Zyklus, während die Gebärmutterschleimhaut abgestossen wird.", en: "Estrogen and progesterone are at their lowest point of the cycle as the uterine lining is shed." }, source: "Reed & Carr, Endotext (2018)" },
      { text: { de: "Prostaglandine, die beim Abbau der Gebärmutterschleimhaut freigesetzt werden, lösen die Muskelkontraktionen aus, die als Krämpfe wahrgenommen werden.", en: "Prostaglandins released during the breakdown of the uterine lining trigger the muscle contractions perceived as cramps." }, source: "Bajalan et al., J Caring Sci (2019)" },
      { text: { de: "Die Hautdurchblutung und Schweissrate sind in der Lutealphase höher als in der frühen Menstruation, was zu spürbaren Unterschieden im Hautgefühl führen kann.", en: "Skin blood flow and sweating rate are higher in the luteal phase than in early menstruation, which can lead to noticeable differences in how skin feels." }, source: "Scoping Review, PMC11703644 (2024)" },
      { text: { de: "Der Eisenverlust durch die Monatsblutung beträgt im Schnitt rund 1 mg, kann bei stärkerer Blutung aber bis zu 14 mg betragen.", en: "Average iron loss through menstrual bleeding is around 1 mg, but can reach up to 14 mg with heavier flow." }, source: "Biologica Research Review (2026)" },
      { text: { de: "Magnesiumkonzentrationen im Blut sind während der Menstruation typischerweise am höchsten und sinken zur späten Follikelphase hin ab.", en: "Blood magnesium concentrations are typically highest during menstruation and decline toward the late follicular phase." }, source: "Tandfonline Cohort Study (2022)" },
      { text: { de: "Eine erhöhte Sympathikus-Aktivität in dieser Phase kann mit niedrigerer Energie und erhöhtem Ruhebedürfnis einhergehen.", en: "Increased sympathetic nervous system activity in this phase can be associated with lower energy and a greater need for rest." }, source: "Sleep & Cardiovascular Review, PMC10656370 (2023)" },
      { text: { de: "Die Basaltemperatur des Körpers ist in der Menstruationsphase niedriger als in der Lutealphase, was den Übergang zwischen den Phasen markiert.", en: "Basal body temperature is lower during menstruation than in the luteal phase, marking the transition between phases." }, source: "Scoping Review, PMC11703644 (2024)" },
      { text: { de: "Die Konzentration von follikelstimulierendem Hormon (FSH) beginnt bereits in den letzten Tagen der vorherigen Lutealphase langsam zu steigen.", en: "Follicle-stimulating hormone (FSH) concentration begins rising slowly in the final days of the preceding luteal phase already." }, source: "Wikipedia, Follicular Phase, zitiert nach Speroff et al." },
      { text: { de: "Studien zur Schmerzwahrnehmung deuten darauf hin, dass die Reaktion auf Entzündungsreize während der Menstruation verstärkt sein kann.", en: "Pain perception studies suggest the response to inflammatory stimuli may be heightened during menstruation." }, source: "MedicineNet Clinical Review (2026)" },
    ],
    mental: [
      { text: { de: "Manche Frauen berichten in der Menstruationsphase über ein erhöhtes Ruhebedürfnis und reduzierte Reizverarbeitung im Vergleich zu anderen Zyklusphasen.", en: "Some women report an increased need for rest and reduced stimulus processing during menstruation compared to other cycle phases." }, source: "Sundström Poromaa & Gingnell, Front Neurosci (2014)" },
      { text: { de: "Introspektion und Rückbesinnung fallen vielen Frauen in dieser Phase leichter als ein starker Aussenfokus.", en: "Introspection and reflection come more easily to many women in this phase than strong outward focus." }, source: "Sundström Poromaa & Gingnell, Front Neurosci (2014)" },
      { text: { de: "Die depressiven Stimmungswerte bei Frauen mit PMS sind in der Lutealphase erhöht, normalisieren sich aber meist innerhalb der ersten Menstruationstage.", en: "Depressive mood scores in women with PMS rise in the luteal phase but typically normalize within the first days of menstruation." }, source: "PLOS One, Pilot Study (2013)" },
      { text: { de: "Mit Einsetzen der Menstruation klingen die in der späten Lutealphase erhöhten PMDD-Symptome bei den meisten Frauen innerhalb von ein bis zwei Tagen ab.", en: "With the onset of menstruation, PMDD symptoms elevated in the late luteal phase subside for most women within one to two days." }, source: "O'Brien et al., zitiert in Frontiers Review (2014)" },
      { text: { de: "Die Konzentrationsfähigkeit beginnt sich für viele Frauen bereits in den letzten Menstruationstagen zu verbessern, parallel zum leichten Anstieg des Östrogenspiegels.", en: "Concentration ability begins improving for many women already in the final days of menstruation, paralleling the slight rise in estrogen." }, source: "Sundström Poromaa & Gingnell, Front Neurosci (2014)" },
      { text: { de: "Studien zur Emotionsregulation zeigen, dass die Verarbeitung negativer Reize in der Menstruationsphase im Vergleich zur Lutealphase tendenziell stabiler ist.", en: "Emotion regulation studies show that processing of negative stimuli tends to be more stable during menstruation compared to the luteal phase." }, source: "ScienceDirect, Window of Vulnerability Study (2022)" },
      { text: { de: "Eine grosse Kohortenstudie mit 3,3 Millionen Frauen aus 109 Ländern bestätigte eine prämenstruelle Stimmungsverschlechterung, die mit Beginn der Menstruation nachlässt.", en: "A large cohort study of 3.3 million women across 109 countries confirmed a premenstrual mood decline that eases with the onset of menstruation." }, source: "Pierson et al. (2021), zitiert in ScienceDirect (2022)" },
      { text: { de: "Der Cortisolspiegel, der in der späten Lutealphase oft erhöht ist, normalisiert sich bei den meisten Frauen mit Beginn der Blutung.", en: "Cortisol levels, often elevated in the late luteal phase, normalize for most women with the onset of bleeding." }, source: "PLOS One, Pilot Study (2013)" },
    ],
    nutrition: [
      { text: { de: "Eisenreiche Lebensmittel wie Linsen, Kürbiskerne oder dunkles Blattgemüse helfen, den Eisenverlust durch die Monatsblutung auszugleichen.", en: "Iron-rich foods like lentils, pumpkin seeds, or dark leafy greens help offset iron loss from menstrual bleeding." }, source: "Biologica Research Review (2026)" },
      { text: { de: "Vitamin C verbessert die Aufnahme von pflanzlichem Eisen erheblich, weshalb die Kombination z.B. von Linsen mit Zitrusfrüchten sinnvoll ist.", en: "Vitamin C significantly improves absorption of plant-based iron, making combinations like lentils with citrus fruit especially useful." }, source: "Ernährungsreview, IJPS Journal (2025)" },
      { text: { de: "Magnesiumreiche Lebensmittel wie Kürbiskerne oder dunkle Schokolade werden mit reduzierter Krampfintensität während der Menstruation in Verbindung gebracht.", en: "Magnesium-rich foods like pumpkin seeds or dark chocolate are associated with reduced cramp intensity during menstruation." }, source: "Wellbeing Nutrition Review (2026)" },
      { text: { de: "Omega-3-Fettsäuren, etwa aus fettem Fisch oder Leinsamen, können laut mehreren Studien die Intensität von Menstruationsschmerzen reduzieren, da sie die Prostaglandin-Produktion dämpfen.", en: "Omega-3 fatty acids, found in fatty fish or flaxseed, may reduce menstrual pain intensity according to several studies, by dampening prostaglandin production." }, source: "Premium Medical Circle Review (2026)" },
      { text: { de: "Koffein und Alkohol werden mit verstärkter Entzündungsreaktion und schlechterer Eisenaufnahme während der Menstruation in Verbindung gebracht.", en: "Caffeine and alcohol are associated with increased inflammatory response and reduced iron absorption during menstruation." }, source: "Premium Medical Circle Review (2026)" },
      { text: { de: "Eine Übersichtsarbeit zu 16 klinischen Studien fand, dass Vitamin B1, D, E, K sowie Calcium, Zink und Bor entzündungshemmende Eigenschaften haben, die mit weniger Menstruationsschmerzen einhergehen können.", en: "A review of 16 clinical studies found that vitamins B1, D, E, K plus calcium, zinc, and boron show anti-inflammatory properties that may relate to less menstrual pain." }, source: "Healthline Clinical Review, zitiert 16 Studien (2022)" },
      { text: { de: "Dunkle Schokolade mit hohem Kakaoanteil (ab 70%) liefert konzentriert Magnesium und Antioxidantien bei vergleichsweise wenig Zucker.", en: "Dark chocolate with high cocoa content (70%+) delivers concentrated magnesium and antioxidants with comparatively less sugar." }, source: "Divine Chocolate Health Review (2025)" },
    ],
  },
  follikel: {
    body: [
      { text: { de: "Follikelstimulierendes Hormon (FSH) regt mehrere Eibläschen in den Eierstöcken zum Wachstum an, während gleichzeitig der Östrogenspiegel steigt.", en: "Follicle-stimulating hormone (FSH) stimulates multiple ovarian follicles to grow while estrogen levels rise simultaneously." }, source: "StatPearls, NCBI Bookshelf (2023)" },
      { text: { de: "Ein dominantes Follikel setzt sich im Verlauf der Phase durch und sondert zunehmend Östradiol ab, was die übrigen Follikel zurücktreten lässt.", en: "A dominant follicle emerges over the course of the phase and increasingly secretes estradiol, causing the remaining follicles to recede." }, source: "ScienceDirect Topics, Follicular Phase Overview" },
      { text: { de: "Der Östradiolspiegel steigt von unter 85 pg/ml in der frühen Phase auf bis zu 400 pg/ml in der späten Follikelphase.", en: "Estradiol levels rise from below 85 pg/ml in the early phase to as much as 400 pg/ml in the late follicular phase." }, source: "ClinicalTrials.gov Protocol, NCT01954966" },
      { text: { de: "Steigende Östrogenwerte regen das Wachstum der Gebärmutterschleimhaut an und bereiten den Körper auf einen möglichen Eisprung vor.", en: "Rising estrogen levels stimulate growth of the uterine lining and prepare the body for a possible ovulation." }, source: "Wikipedia, Follicular Phase, zitiert nach Speroff et al." },
      { text: { de: "Die Follikelphase ist mit 14 bis 21 Tagen die längste und variabelste Phase des Zyklus, im Gegensatz zur recht konstanten Lutealphase.", en: "At 14 to 21 days, the follicular phase is the longest and most variable phase of the cycle, unlike the relatively constant luteal phase." }, source: "Cleveland Clinic, Follicular Phase Overview (2026)" },
      { text: { de: "Gegen Ende der Phase löst der hohe Östrogenspiegel über positive Rückkopplung einen Anstieg von LH und FSH aus, der den Eisprung einleitet.", en: "Toward the end of the phase, high estrogen triggers a rise in LH and FSH via positive feedback, initiating ovulation." }, source: "Scoping Review, PMC11703644 (2024)" },
      { text: { de: "FGF21, ein Stoffwechselhormon, ist in der Follikelphase signifikant niedriger als in der Lutealphase und korreliert positiv mit der Aktivität des braunen Fettgewebes.", en: "FGF21, a metabolic hormone, is significantly lower in the follicular phase than in the luteal phase and correlates positively with brown adipose tissue activity." }, source: "PMC11446134, Brown Adipose Tissue Study (2024)" },
      { text: { de: "Die Schweissrate ist in der frühen Follikelphase oft höher als in der mittleren Lutealphase, entgegen mancher verbreiteter Annahmen.", en: "Sweating rate is often higher in the early follicular phase than in the mid-luteal phase, contrary to some common assumptions." }, source: "Scoping Review, PMC11703644 (2024)" },
    ],
    mental: [
      { text: { de: "Die Reaktionsfähigkeit bei der Auflösung emotionaler Konflikte ist in der Follikelphase tendenziell schneller als in der Lutealphase.", en: "Reaction time for resolving emotional conflict tends to be faster in the follicular phase than in the luteal phase." }, source: "PLOS One, Pilot Study (2013)" },
      { text: { de: "Die Belohnungsempfindlichkeit, ein möglicher Biomarker für Stimmung, ist in mehreren Studien in der Follikelphase am höchsten.", en: "Reward responsivity, a possible biomarker for mood, appears highest in the follicular phase across several studies." }, source: "Psychiatric Symptoms Review, PMC8906247 (2022)" },
      { text: { de: "Manche gesunden Frauen berichten in der frühen Follikelphase über höhere depressive Symptomwerte im Vergleich zur mittleren Lutealphase.", en: "Some healthy women report higher depressive symptom scores in the early follicular phase compared to the mid-luteal phase." }, source: "Psychiatric Symptoms Review, PMC8906247 (2022)" },
      { text: { de: "Positive Assoziationen zwischen Östradiol und der Konnektivität des Hippocampus deuten auf mögliche kognitive Vorteile in östrogenreichen Phasen hin.", en: "Positive associations between estradiol and hippocampal connectivity suggest possible cognitive benefits during estrogen-rich phases." }, source: "bioRxiv, Resting-State Connectivity Study (2024)" },
      { text: { de: "Mit steigendem Östrogen wird in mehreren Studien eine Verbesserung von Stimmung und Energie zur späten Follikelphase hin beobachtet.", en: "As estrogen rises, several studies observe improved mood and energy toward the late follicular phase." }, source: "Mid-Cycle Mood Study, PMC9856962 (2023)" },
      { text: { de: "Frauen mit ADHS zeigen Hinweise auf bessere Aufmerksamkeitsleistung in östrogendominierten Phasen verglichen mit der Lutealphase.", en: "Women with ADHD show signs of better attentional performance during estrogen-dominant phases compared to the luteal phase." }, source: "Narrative Review, PMC12786913 (2026)" },
    ],
    nutrition: [
      { text: { de: "Zinkreiche Lebensmittel wie Kürbiskerne unterstützen laut Forschung die Synthese von follikelstimulierendem Hormon (FSH) und luteinisierendem Hormon (LH).", en: "Zinc-rich foods like pumpkin seeds support FSH and LH synthesis according to research." }, source: "Minerals Review, PMC11013220 (2024)" },
      { text: { de: "Eisenreiches, dunkles Blattgemüse wie Grünkohl und Spinat wird für die Follikelphase empfohlen, um die Eisenspeicher nach der Menstruation wieder aufzubauen.", en: "Iron-rich dark leafy greens like kale and spinach are recommended for the follicular phase to replenish iron stores after menstruation." }, source: "Hormona Follicular Foods Review (2025)" },
      { text: { de: "Komplexe Kohlenhydrate wie Vollkorn, Quinoa oder Hafer liefern in dieser Phase eine gleichmässigere Energiefreisetzung als einfache Zucker.", en: "Complex carbohydrates like whole grains, quinoa, or oats provide steadier energy release in this phase compared to simple sugars." }, source: "Hello Period Cycle Nutrition Review (2023)" },
      { text: { de: "Magnesiumkonzentrationen im Blut sinken typischerweise zur späten Follikelphase hin ab, was eine bewusste Zufuhr sinnvoll macht.", en: "Blood magnesium concentrations typically decline toward the late follicular phase, making conscious intake worthwhile." }, source: "Tandfonline Cohort Study (2022)" },
      { text: { de: "Phytoöstrogenhaltige Lebensmittel wie Leinsamen werden traditionell mit der Östrogenregulation in der ersten Zyklushälfte in Verbindung gebracht.", en: "Phytoestrogen-containing foods like flaxseed are traditionally associated with estrogen regulation in the first half of the cycle." }, source: "Wikipedia, Seed Cycling Overview (2026)" },
      { text: { de: "Eine ausreichende Proteinzufuhr wird in der Follikelphase mit der Unterstützung von Follikelwachstum und Hormonsynthese in Verbindung gebracht.", en: "Adequate protein intake in the follicular phase is associated with supporting follicle growth and hormone synthesis." }, source: "Buddharthi Archana, IJPS Journal (2025)" },
    ],
  },
  ovulation: {
    body: [
      { text: { de: "Ein starker Anstieg des luteinisierenden Hormons (LH) löst den Eisprung aus und führt zur Freisetzung der reifen Eizelle.", en: "A surge in luteinizing hormone (LH) triggers ovulation and releases the mature egg." }, source: "StatPearls, NCBI Bookshelf (2023)" },
      { text: { de: "Die Hautelastizität ist während des Eisprungs im Vergleich zur Follikelphase erhöht, was auf den Einfluss des Östrogenspiegels zurückgeführt wird.", en: "Skin elasticity is increased during ovulation compared to the follicular phase, attributed to estrogen's influence." }, source: "Scoping Review, PMC11703644 (2024)" },
      { text: { de: "Die degenerierte Follikelhülle wandelt sich nach dem Eisprung in den Gelbkörper (Corpus luteum) um, der fortan Progesteron produziert.", en: "The collapsed follicle transforms into the corpus luteum after ovulation, which then produces progesterone." }, source: "Scoping Review, PMC11703644 (2024)" },
      { text: { de: "Der Eisprung markiert den Übergang von hohem Östrogen/niedrigem Progesteron zu der Kombination aus hohem Östrogen und ansteigendem Progesteron.", en: "Ovulation marks the transition from high estrogen/low progesterone to a combination of high estrogen and rising progesterone." }, source: "Exercise Performance Review, PMC7497427 (2020)" },
      { text: { de: "Die fruchtbarste Zeitspanne umfasst die letzten Tage der Follikelphase bis unmittelbar nach dem Eisprung.", en: "The most fertile window spans the final days of the follicular phase through immediately after ovulation." }, source: "Cleveland Clinic, Follicular Phase Overview (2026)" },
      { text: { de: "Während des Eisprungs erreicht die Östradiolkonzentration typischerweise ihren höchsten Wert im gesamten Zyklus.", en: "During ovulation, estradiol concentration typically reaches its highest level of the entire cycle." }, source: "ClinicalTrials.gov Protocol, NCT01954966" },
    ],
    mental: [
      { text: { de: "Die positive Stimmung erreicht laut einer Pilotstudie mit 60 gesunden Frauen ihren Höhepunkt in der späten Follikelphase rund um den Eisprung.", en: "Positive mood peaks, according to a pilot study with 60 healthy women, in the late follicular phase around ovulation." }, source: "Mid-Cycle Mood Study, PMC9856962 (2023)" },
      { text: { de: "Negative Stimmungsdimensionen wie Angst, Erschöpfung und Reizbarkeit waren in derselben Studie zur Zeit des Eisprungs am niedrigsten ausgeprägt.", en: "Negative mood dimensions such as anxiety, fatigue, and hostility were lowest expressed around the time of ovulation in the same study." }, source: "Mid-Cycle Mood Study, PMC9856962 (2023)" },
      { text: { de: "Die Belohnungsempfindlichkeit des Gehirns gilt rund um den Eisprung tendenziell als hoch, was mit gehobener Stimmung in Verbindung gebracht wird.", en: "Brain reward responsivity tends to be high around ovulation, associated with elevated mood." }, source: "Psychiatric Symptoms Review, PMC8906247 (2022)" },
      { text: { de: "Hohe Östrogenwerte rund um den Eisprung werden mit positiven Effekten auf Hippocampus-Volumen und neuronale Konnektivität in Verbindung gebracht.", en: "High estrogen levels around ovulation are linked to positive effects on hippocampal volume and neural connectivity." }, source: "bioRxiv, Resting-State Connectivity Study (2024)" },
      { text: { de: "Die Konzentrationsfähigkeit gilt in mehreren Übersichtsarbeiten als günstig in den östrogendominierten Tagen rund um den Eisprung.", en: "Concentration ability is considered favorable in several reviews during the estrogen-dominant days around ovulation." }, source: "Sundström Poromaa & Gingnell, Front Neurosci (2014)" },
    ],
    nutrition: [
      { text: { de: "Antioxidantienreiche Beeren werden in mehreren Übersichtsarbeiten zur Unterstützung der reproduktiven Gesundheit rund um den Eisprung empfohlen.", en: "Antioxidant-rich berries are recommended in several reviews to support reproductive health around ovulation." }, source: "Elara Care, Menstrual Cycle Food Chart (2023)" },
      { text: { de: "Vitamin-E-reiche Nüsse und Samen wie Mandeln und Sonnenblumenkerne werden mit antioxidativen Effekten in dieser Phase in Verbindung gebracht.", en: "Vitamin E-rich nuts and seeds like almonds and sunflower seeds are linked to antioxidant effects in this phase." }, source: "Hello Period Cycle Nutrition Review (2023)" },
      { text: { de: "Leichtere, frische Mahlzeiten mit viel Gemüse werden in der Ovulationsphase häufig empfohlen, da der Energiestoffwechsel besonders aktiv ist.", en: "Lighter, fresh meals with plenty of vegetables are often recommended during ovulation, as metabolism is particularly active." }, source: "Premium Medical Circle Review (2026)" },
      { text: { de: "Magere Proteinquellen wie Fisch oder Hühnchen werden in Kombination mit komplexen Kohlenhydraten für eine ausgewogene Energiezufuhr rund um den Eisprung genannt.", en: "Lean protein sources like fish or chicken combined with complex carbohydrates are noted for balanced energy intake around ovulation." }, source: "Elara Care, Menstrual Cycle Food Chart (2023)" },
      { text: { de: "Ausreichende Flüssigkeitszufuhr wird in dieser Phase besonders betont, da der Grundumsatz leicht ansteigen kann.", en: "Adequate fluid intake is particularly emphasized in this phase, as basal metabolic rate can rise slightly." }, source: "Premium Medical Circle Review (2026)" },
    ],
  },
  luteal: {
    body: [
      { text: { de: "Nach dem Eisprung produziert der Gelbkörper (Corpus luteum) Progesteron, das Hauptkennzeichen der Lutealphase.", en: "After ovulation, the corpus luteum produces progesterone, the defining hormone of the luteal phase." }, source: "Scoping Review, PMC11703644 (2024)" },
      { text: { de: "Sowohl Östradiol als auch Progesteron sind in der Lutealphase signifikant höher als in der Follikelphase.", en: "Both estradiol and progesterone are significantly higher in the luteal phase than in the follicular phase." }, source: "PMC11446134, Brown Adipose Tissue Study (2024)" },
      { text: { de: "Die Basaltemperatur des Körpers ist in der Lutealphase höher als in der Follikelphase, was zur Zyklusverfolgung genutzt werden kann.", en: "Basal body temperature is higher in the luteal phase than in the follicular phase, which can be used for cycle tracking." }, source: "Scoping Review, PMC11703644 (2024)" },
      { text: { de: "Die Hautdurchblutung und Schweissrate sind in der mittleren Lutealphase signifikant erhöht im Vergleich zur Follikelphase.", en: "Skin blood flow and sweating rate are significantly increased in the mid-luteal phase compared to the follicular phase." }, source: "Scoping Review, PMC11703644 (2024)" },
      { text: { de: "FSH bleibt während der gesamten Lutealphase niedrig, was die Entwicklung neuer Follikel in dieser Zeit verhindert.", en: "FSH remains low throughout the luteal phase, preventing development of new follicles during this time." }, source: "StatPearls, NCBI Bookshelf (2023)" },
      { text: { de: "Ohne Befruchtung baut sich der Gelbkörper gegen Ende der Lutealphase ab, was zum Abfall von Progesteron und Östrogen führt.", en: "Without fertilization, the corpus luteum degrades toward the end of the luteal phase, leading to a drop in progesterone and estrogen." }, source: "Scoping Review, PMC11703644 (2024)" },
      { text: { de: "Der Energiebedarf steigt in der Lutealphase laut mehreren Untersuchungen um mehrere hundert Kalorien täglich im Vergleich zur Follikelphase.", en: "Energy needs in the luteal phase rise by several hundred calories daily compared to the follicular phase, according to several studies." }, source: "Biologica Research Review (2026)" },
      { text: { de: "Die Lutealphase ist mit durchschnittlich etwa 14 Tagen deutlich konstanter in der Länge als die variablere Follikelphase.", en: "At an average of about 14 days, the luteal phase length is much more constant than the more variable follicular phase." }, source: "Cleveland Clinic, Follicular Phase Overview (2026)" },
    ],
    mental: [
      { text: { de: "Frauen mit PMS zeigen in der späten Lutealphase signifikant erhöhte Depressionswerte im Vergleich zur Follikelphase.", en: "Women with PMS show significantly elevated depression scores in the late luteal phase compared to the follicular phase." }, source: "PLOS One, Pilot Study (2013)" },
      { text: { de: "Die Auflösung emotionaler Konflikte dauert in der Lutealphase bei gesunden Frauen länger als in der Follikelphase.", en: "Resolving emotional conflict takes longer in the luteal phase for healthy women compared to the follicular phase." }, source: "PLOS One, Pilot Study (2013)" },
      { text: { de: "Prämenstruelle emotionale Schwankungen werden konsistent mit der Progesteronexposition in der Lutealphase in Verbindung gebracht.", en: "Premenstrual emotional fluctuations are consistently linked to progesterone exposure during the luteal phase." }, source: "Sundström Poromaa & Gingnell, Front Neurosci (2014)" },
      { text: { de: "Etwa 2-10% der Frauen im gebärfähigen Alter erleben starke prämenstruelle Symptome, 2-5% erfüllen die Kriterien für PMDD.", en: "About 2-10% of women of reproductive age experience severe premenstrual symptoms, with 2-5% meeting criteria for PMDD." }, source: "O'Brien et al. (2011), zitiert in Frontiers Review (2014)" },
      { text: { de: "Die Belohnungsempfindlichkeit des Gehirns gilt in der Lutealphase laut mehreren Studien als am niedrigsten im Zyklusverlauf.", en: "Brain reward responsivity is considered lowest in the luteal phase across the cycle according to several studies." }, source: "Psychiatric Symptoms Review, PMC8906247 (2022)" },
      { text: { de: "Bei Stressexposition in der mittleren Lutealphase berichten Frauen über mehr Belastung als in der frühen Follikelphase.", en: "When exposed to stress in the mid-luteal phase, women report more distress than in the early follicular phase." }, source: "ScienceDirect, Window of Vulnerability Study (2022)" },
      { text: { de: "Psychomotorische Verlangsamung wurde bei Frauen mit PMDD speziell während der Lutealphase im Vergleich zu Kontrollgruppen beobachtet.", en: "Psychomotor slowing was observed in women with PMDD specifically during the luteal phase compared to control groups." }, source: "Resnick et al. (1998), zitiert in PMC2491904" },
      { text: { de: "Cortisol-Werte können in der späten Lutealphase bei Frauen mit prämenstruellen Symptomen leicht erhöht sein.", en: "Cortisol levels may be slightly elevated in the late luteal phase in women with premenstrual symptoms." }, source: "PLOS One, Pilot Study (2013)" },
    ],
    nutrition: [
      { text: { de: "Magnesiumreiche Lebensmittel werden mit der Linderung von PMS-Symptomen wie Stimmungsschwankungen und Wassereinlagerungen in Verbindung gebracht.", en: "Magnesium-rich foods are associated with relief of PMS symptoms such as mood swings and water retention." }, source: "Nutrition During the Menstrual Cycle Review (2026)" },
      { text: { de: "Komplexe Kohlenhydrate und ballaststoffreiche Lebensmittel werden für die Lutealphase empfohlen, um Blutzuckerschwankungen abzufedern.", en: "Complex carbohydrates and fiber-rich foods are recommended for the luteal phase to buffer blood sugar fluctuations." }, source: "Asan UK, Luteal Phase Nutrition Review (2026)" },
      { text: { de: "Vitamin B6 wird konsistent mit der Unterstützung des Stimmungsgleichgewichts während der Lutealphase in Verbindung gebracht, besonders kombiniert mit Magnesium.", en: "Vitamin B6 is consistently linked to supporting mood balance during the luteal phase, especially when combined with magnesium." }, source: "Biologica Research Review (2026)" },
      { text: { de: "Calcium- und Magnesiumzufuhr werden in der Lutealphase besonders betont, da der Bedarf laut mehreren Studien in dieser Phase steigt.", en: "Calcium and magnesium intake are particularly emphasized in the luteal phase, as needs rise during this period according to several studies." }, source: "Buddharthi Archana, IJPS Journal (2025)" },
      { text: { de: "Koffein und Alkohol werden mit verstärkten PMS-Symptomen und schlechterer Schlafqualität in der Lutealphase in Verbindung gebracht.", en: "Caffeine and alcohol are associated with worsened PMS symptoms and reduced sleep quality during the luteal phase." }, source: "Premium Medical Circle Review (2026)" },
      { text: { de: "Dunkle Schokolade mit hohem Kakaoanteil liefert Magnesium, das mit der Senkung von Prostaglandinen und somit weniger Krämpfen in Verbindung gebracht wird.", en: "High-cocoa dark chocolate provides magnesium, linked to lowering prostaglandins and therefore fewer cramps." }, source: "Experience Life Nutrition Review (2026)" },
    ],
  },
};

// Zieht zufällig einen Fakt aus jeder der drei Kategorien für eine Phase.
export function drawRandomFacts(phaseKey) {
  const pool = PHASE_FACTS[phaseKey];
  const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
  return {
    body: pick(pool.body),
    mental: pick(pool.mental),
    nutrition: pick(pool.nutrition),
  };
}
